x_dim: 3
z_dim: 3
a_dim: 3
lr: 0.001
horizon: 100
ou_theta: 0.15
ou_sigma: 0.1

max_riccati_updates: 100
train_batch_size: 100
replay_buffer_size: 100000
discount_rate: 1.0

encoder_layers: [64,64]

l2_reg_scale: 0.1

dynamics_weight: 1.0
cost_weight: 1.0
td_weight: 0.0

x_dynamics_weight: 0.001
reconstruction_weight: 0.001


P_lr: 1.0

l1_reg_weight: 0.01
l2_Q_reg_weight: 0.0

min_a: -1.0
max_a: 1.0

