x_dim: 3
z_dim: 3
a_dim: 3
lr: 0.0001
horizon: 100
ou_theta: 0.15
ou_sigma: 0.1

max_riccati_updates: 100
train_batch_size: 100
replay_buffer_size: 100000
discount_rate: 0.9

encoder_layers: [64,64]

dynamics_weight: 1.0
cost_weight: 1.0
td_weight: 0.0

l1_reg_weight: 0.01

min_a: -1.0
max_a: 1.0